### ISSUE TITLE
关于是否违规的问题

### ISSUE THREAD

**Issue by migo-robben** [NanmiCoder/CrawlerTutorial#6]
你好，在一些网站或者帖子可以看到关于你刚关闭不久的项目（用于爬取一些媒体平台数据），我想问如果只是爬取数据，进行数据分析和学习，不用于任何商业行为，不用于交易，不用于谋取利益，不泄露等。这样的爬虫合规吗，因为我看到，例如某书的 robots.txt，是这样的 “User-agent:* Disallow:/”；在此情况下，还能爬取这个网站的数据吗？

**Comment by NanmiCoder** [comment]
不追究啥事没有。我的理解个人分析和学习这些应该问题不大，注意也只是应该。。。。。也就是主动权在别人手里
